task_col: COBRA_ood # Column containing labels for the task
extra_cols: [] # Any extra columns needed to perform the task (e.g. survival tasks)
task_type: "classification"

metrics: # List of one or more performance metrics to report (this is used for automated result compilation when using Patho-Bench in advanced mode)
  - macro-ovr-auc
  - acc
  - macro-f1
  - weighted-f1

folds: 5 # Number of cross-validation folds to use (only used in advanced mode)

label_dict: # Dictionary of integer labels to string labels
  0: 'B07'
  1: 'C43.9'
  2: 'C44.9'
  3: 'C79.2'
  4: 'C81-C96'
  5: 'D03.9'
  6: 'D04.9'
  7: 'D18.0'
  8: 'D22.9'
  9: 'D23.9'
  10: 'K04.8'
  11: 'L57.0'
  12: 'L72.0'
  13: 'L82'
  14: 'L90.5'
  15: 'other'

sample_col: slide_id # Column containing the unit of analysis. Use 'case_id' for patient-level tasks and 'slide_id' for slide-level tasks.
